Update to SABnzbdPlus 0.7.x

diff --git a/package_routines b/package_routines
--- a/package_routines
+++ b/package_routines
@@ -1,8 +1,132 @@
 ######################################################################
+# List of available definitions (it's not necessary to uncomment them)
+######################################################################
+###### Command definitions #####
+#CMD_AWK="/bin/awk"
+#CMD_CAT="/bin/cat"
+#CMD_CHMOD="/bin/chmod"
+#CMD_CHOWN="/bin/chown"
+#CMD_CP="/bin/cp"
+#CMD_CUT="/bin/cut"
+#CMD_DATE="/bin/date"
+#CMD_ECHO="/bin/echo"
+#CMD_EXPR="/usr/bin/expr"
+#CMD_FIND="/usr/bin/find"
+#CMD_GETCFG="/sbin/getcfg"
+#CMD_GREP="/bin/grep"
+#CMD_GZIP="/bin/gzip"
+#CMD_HOSTNAME="/bin/hostname"
+#CMD_LN="/bin/ln"
+#CMD_LOG_TOOL="/sbin/log_tool"
+#CMD_MD5SUM="/bin/md5sum"
+#CMD_MKDIR="/bin/mkdir"
+#CMD_MV="/bin/mv"
+#CMD_RM="/bin/rm"
+#CMD_RMDIR="/bin/rmdir"
+#CMD_SED="/bin/sed"
+#CMD_SETCFG="/sbin/setcfg"
+#CMD_SLEEP="/bin/sleep"
+#CMD_SORT="/usr/bin/sort"
+#CMD_SYNC="/bin/sync"
+#CMD_TAR="/bin/tar"
+#CMD_TOUCH="/bin/touch"
+#CMD_WGET="/usr/bin/wget"
+#CMD_WLOG="/sbin/write_log"
+#CMD_XARGS="/usr/bin/xargs"
+#CMD_7Z="/usr/local/sbin/7z"
+#
+###### System definitions #####
+#SYS_EXTRACT_DIR="$(pwd)"
+#SYS_CONFIG_DIR="/etc/config"
+#SYS_INIT_DIR="/etc/init.d"
+#SYS_STARTUP_DIR="/etc/rcS.d"
+#SYS_SHUTDOWN_DIR="/etc/rcK.d"
+#SYS_RSS_IMG_DIR="/home/httpd/RSS/images"
+#SYS_QPKG_DATA_FILE_GZIP="./data.tar.gz"
+#SYS_QPKG_DATA_FILE_BZIP2="./data.tar.bz2"
+#SYS_QPKG_DATA_FILE_7ZIP="./data.tar.7z"
+#SYS_QPKG_DATA_CONFIG_FILE="./conf.tar.gz"
+#SYS_QPKG_DATA_MD5SUM_FILE="./md5sum"
+#SYS_QPKG_DATA_PACKAGES_FILE="./Packages.gz"
+#SYS_QPKG_CONFIG_FILE="$SYS_CONFIG_DIR/qpkg.conf"
+#SYS_QPKG_CONF_FIELD_QPKGFILE="QPKG_File"
+#SYS_QPKG_CONF_FIELD_NAME="Name"
+#SYS_QPKG_CONF_FIELD_VERSION="Version"
+#SYS_QPKG_CONF_FIELD_ENABLE="Enable"
+#SYS_QPKG_CONF_FIELD_DATE="Date"
+#SYS_QPKG_CONF_FIELD_SHELL="Shell"
+#SYS_QPKG_CONF_FIELD_INSTALL_PATH="Install_Path"
+#SYS_QPKG_CONF_FIELD_CONFIG_PATH="Config_Path"
+#SYS_QPKG_CONF_FIELD_WEBUI="WebUI"
+#SYS_QPKG_CONF_FIELD_WEBPORT="Web_Port"
+#SYS_QPKG_CONF_FIELD_SERVICEPORT="Service_Port"
+#SYS_QPKG_CONF_FIELD_SERVICE_PIDFILE="Pid_File"
+#SYS_QPKG_CONF_FIELD_AUTHOR="Author"
+#SYS_QPKG_CONF_FIELD_RC_NUMBER="RC_Number"
+## The following variables are assigned values at run-time.
+#SYS_HOSTNAME=$($CMD_HOSTNAME)
+## Data file name (one of SYS_QPKG_DATA_FILE_GZIP, SYS_QPKG_DATA_FILE_BZIP2,
+## or SYS_QPKG_DATA_FILE_7ZIP)
+#SYS_QPKG_DATA_FILE=
+## Base location.
+#SYS_QPKG_BASE=""
+## Base location of QPKG installed packages.
+#SYS_QPKG_INSTALL_PATH=""
+## Location of installed software.
+#SYS_QPKG_DIR=""
+## If the QPKG should be enabled or disabled after the installation/upgrade.
+SYS_QPKG_SERVICE_ENABLED="TRUE"
+## Architecture of the device the QPKG is installed on.
+#SYS_CPU_ARCH=""
+## Name and location of system shares
+#SYS_PUBLIC_SHARE=""
+#SYS_PUBLIC_PATH=""
+#SYS_DOWNLOAD_SHARE=""
+#SYS_DOWNLOAD_PATH=""
+#SYS_MULTIMEDIA_SHARE=""
+#SYS_MULTIMEDIA_PATH=""
+#SYS_RECORDINGS_SHARE=""
+#SYS_RECORDINGS_PATH=""
+#SYS_USB_SHARE=""
+#SYS_USB_PATH=""
+#SYS_WEB_SHARE=""
+#SYS_WEB_PATH=""
+## Path to ipkg or opkg package tool if installed.
+#CMD_PKG_TOOL=
+#
+
+# Find the Public share
+PUBLIC_SHARE=`/sbin/getcfg SHARE_DEF defPublic -d Public -f /etc/config/def_share.info`
+
+# Determine BASE installation location according to smb.conf
+BASE=
+publicdir=`/sbin/getcfg $PUBLIC_SHARE path -f /etc/config/smb.conf`
+if [ ! -z $publicdir ] && [ -d $publicdir ];then
+  publicdirp1=`/bin/echo $publicdir | /bin/cut -d "/" -f 2`
+  publicdirp2=`/bin/echo $publicdir | /bin/cut -d "/" -f 3`
+  publicdirp3=`/bin/echo $publicdir | /bin/cut -d "/" -f 4`
+  if [ ! -z $publicdirp1 ] && [ ! -z $publicdirp2 ] && [ ! -z $publicdirp3 ]; then
+    [ -d "/${publicdirp1}/${publicdirp2}/${PUBLIC_SHARE}" ] && BASE="/${publicdirp1}/${publicdirp2}"
+  fi
+fi
+
+# Determine BASE installation location by checking where the Public folder is.
+if [ -z $BASE ]; then
+  for datadirtest in /share/HDA_DATA /share/HDB_DATA /share/HDC_DATA /share/HDD_DATA /share/MD0_DATA; do
+    [ -d $datadirtest/$PUBLIC_SHARE ] && BASE="/${publicdirp1}/${publicdirp2}"
+  done
+fi
+if [ -z $BASE ] ; then
+  echo "The Public share not found."
+  /sbin/write_log "[SABnzbd] The Public share not found." 1
+  exit 1
+fi
+
+######################################################################
 # All package specific functions shall call 'err_log MSG' if an error
 # is detected that shall terminate the installation.
 ######################################################################
-
+#
 ######################################################################
 # Define any package specific operations that shall be performed when
 # the package is removed.
@@ -10,100 +134,46 @@
 #PKG_PRE_REMOVE="{
 #}"
 #
-
-PKG_MAIN_REMOVE="{
-#removing stuff that doesn't exist isn't a real issue so we just try to cleanup for all versions at once
-#x19 and x86 (-f flag to prevent errors on deleting files that do not exist)
-/bin/rm -f "/usr/bin/ionice"
-/bin/rm -f "/opt/lib/python2.6/site-packages/yenc.py"
-/bin/rm -f "/opt/lib/python2.6/site-packages/_yenc.so"
-#x09 only
-/bin/rm -f "/mnt/HDA_ROOT/rootfs_2_3_6/usr/bin/ionice"
-/bin/rm -f "/mnt/HDA_ROOT/rootfs_2_3_6/opt/lib/python2.6/site-packages/yenc.py"
-/bin/rm -f "/mnt/HDA_ROOT/rootfs_2_3_6/opt/lib/python2.6/site-packages/_yenc.so"
-}"
-
-#
-#PKG_POST_REMOVE="{
+#PKG_MAIN_REMOVE="{
 #}"
+#
+PKG_POST_REMOVE="{
+	# Removing folders in Public share
+	[ -d ${BASE}/${PUBLIC_SHARE}/Downloads ]; then $CMD_RM -rf ${BASE}/${PUBLIC_SHARE}/Downloads
+	[ -d ${BASE}/${PUBLIC_SHARE}/nzb ]; then $CMD_RM -rf ${BASE}/${PUBLIC_SHARE}/nzb
+
+	# Removing Library links
+	if [ -f /usr/bin/ionice ]; then $CMD_RM -f /usr/bin/ionice ; fi
+    if [ -f /opt/lib/python2.6/site-packages/yenc.py ]; then $CMD_RM -f /opt/lib/python2.6/site-packages/yenc.py ; fi
+    if [ -f /opt/lib/python2.6/site-packages/_yenc.so ]; then $CMD_RM -f /opt/lib/python2.6/site-packages/_yenc.so ; fi
+}"
 #
 ######################################################################
 # Define any package specific initialization that shall be performed
 # before the package is installed.
 ######################################################################
-pkg_init(){
-	[ -d "$QPKG_ROOTFS" ] || QPKG_ROOTFS=""
-}
+#pkg_init(){
+#}
 #
 ######################################################################
 # Define any package specific requirement checks that shall be
 # performed before the package is installed.
 ######################################################################
-pkg_check_requirement(){
-	[ -d "$SYS_DOWNLOAD_PATH" ] || err_log "cannot find the Download share"
-}
-
-
+#pkg_check_requirement(){
+#}
+#
 ######################################################################
 # Define any package specific operations that shall be performed when
 # the package is installed.
 ######################################################################
-pkg_pre_install(){
-	# as stopping the previous versions of sab does not always work because of a bug in ps in 3.40
-	# we need to manually kill it to be certain it really will work fine.
-	for pid in $(/bin/pidof python); do
-	  /bin/grep -q "SABnzbd.py" /proc/$pid/cmdline && /bin/kill $pid
-	done
-	/bin/sleep 5
-
-	#remove left over config files which may exist because of previous bugs
-	cd ${SYS_QPKG_DIR}
-	rfiles=$(/usr/bin/find ./ -type f  -name '*qdkorig')
-	for rfile in $rfiles; do /bin/mv $rfile; done
-	rfiles=$(/usr/bin/find ./ -type f  -name '*qdksave')
-	for rfile in $rfiles; do /bin/rm $rfile; done
-}
-
+#pkg_pre_install(){
+#}
 #
 pkg_install(){
-	# create symbolic links for required bin-utils and library files
-    $CMD_LN -sf "${SYS_QPKG_DIR}/bin-utils/ionice" "/usr/bin/ionice"
-	$CMD_LN -sf "${SYS_QPKG_DIR}/lib/_yenc.so" "/opt/lib/python2.6/site-packages/_yenc.so" 
-	$CMD_LN -sf "${SYS_QPKG_DIR}/lib/yenc.py" "/opt/lib/python2.6/site-packages/yenc.py" 
-
-	#check if this is an upgrade from an older version (<0.6), and copy the config file in that case
-	[ -d "${QPKG_ROOTFS}${SYS_QPKG_DIR}/root" ] && $CMD_CP "${QPKG_ROOTFS}${SYS_QPKG_DIR}/root/.sabnzbd/sabnzbd.ini" ${QPKG_ROOTFS}${SYS_QPKG_DIR}/Config/ && $CMD_RM -r "${QPKG_ROOTFS}${SYS_QPKG_DIR}/root"
-	
-	#check if there is already an ini file (upgrading), if not put the default one into place
-	[ -f "${QPKG_ROOTFS}$SYS_QPKG_DIR/Config/sabnzbd.ini" ] || $CMD_MV  ${QPKG_ROOTFS}$SYS_QPKG_DIR/Config/sabnzbd.ini.org ${QPKG_ROOTFS}$SYS_QPKG_DIR/Config/sabnzbd.ini
-
- 	#reset ip config to be sure it all will work with other packages like Sickbeard and Couchpotato
-	$CMD_SETCFG misc host "0.0.0.0" -f ${QPKG_ROOTFS}$SYS_QPKG_DIR/Config/sabnzbd.ini
-	
-	#Configure SABNZBD to use Download or Qdownload, depending on what was found
-        $CMD_SETCFG misc log_dir $SYS_DOWNLOAD_PATH/sabnzbd/logs -f ${QPKG_ROOTFS}$SYS_QPKG_DIR/Config/sabnzbd.ini
-        $CMD_SETCFG misc download_dir $SYS_DOWNLOAD_PATH/sabnzbd/incomplete -f ${QPKG_ROOTFS}$SYS_QPKG_DIR/Config/sabnzbd.ini
-        $CMD_SETCFG misc complete_dir $SYS_DOWNLOAD_PATH/sabnzbd/complete -f ${QPKG_ROOTFS}$SYS_QPKG_DIR/Config/sabnzbd.ini
-        $CMD_SETCFG misc nzb_backup_dir $SYS_DOWNLOAD_PATH/sabnzbd/nzb/backup -f ${QPKG_ROOTFS}$SYS_QPKG_DIR/Config/sabnzbd.ini
-        $CMD_SETCFG misc cache_dir $SYS_DOWNLOAD_PATH/sabnzbd/cache -f ${QPKG_ROOTFS}$SYS_QPKG_DIR/Config/sabnzbd.ini
-        $CMD_SETCFG misc dirscan_dir $SYS_DOWNLOAD_PATH/sabnzbd/nzb -f ${QPKG_ROOTFS}$SYS_QPKG_DIR/Config/sabnzbd.ini
-
-	#Creates all directories needed for sabnzbd download structure
-        $CMD_MKDIR -p "$SYS_DOWNLOAD_PATH/sabnzbd"
-        $CMD_CHMOD 777 $SYS_DOWNLOAD_PATH/sabnzbd
-        $CMD_MKDIR -p "$SYS_DOWNLOAD_PATH/sabnzbd/cache"
-        $CMD_CHMOD 777 $SYS_DOWNLOAD_PATH/sabnzbd/cache
-        $CMD_MKDIR -p "$SYS_DOWNLOAD_PATH/sabnzbd/complete"
-        $CMD_CHMOD 777 $SYS_DOWNLOAD_PATH/sabnzbd/complete
-        $CMD_MKDIR -p "$SYS_DOWNLOAD_PATH/sabnzbd/incomplete"
-        $CMD_CHMOD 777 $SYS_DOWNLOAD_PATH/sabnzbd/incomplete
-        $CMD_MKDIR -p "$SYS_DOWNLOAD_PATH/sabnzbd/logs"
-        $CMD_CHMOD 777 $SYS_DOWNLOAD_PATH/sabnzbd/logs
-        $CMD_MKDIR -p "$SYS_DOWNLOAD_PATH/sabnzbd/nzb"
-        $CMD_CHMOD 777 $SYS_DOWNLOAD_PATH/sabnzbd/nzb
-        $CMD_MKDIR -p "$SYS_DOWNLOAD_PATH/sabnzbd/nzb/backup"
-        $CMD_CHMOD 777 $SYS_DOWNLOAD_PATH/sabnzbd/nzb/backup
+	# Create folders in Public share
+	[ -d ${BASE}/${PUBLIC_SHARE}/Downloads ] || mkdir ${BASE}/${PUBLIC_SHARE}/Downloads
+	[ -d ${BASE}/${PUBLIC_SHARE}/nzb ] || mkdir ${BASE}/${PUBLIC_SHARE}/nzb
 }
-
+#
 #pkg_post_install(){
 #}
